version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672" 
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS} 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

volumes:
  rabbitmq_data:
